Fix catch ci cd errors (#10)
* fix: catch cross platform debug command errors

* fix: install rust before building

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -111,13 +111,15 @@ jobs:
             asset_suffix: windows-x86_64
     steps:
       - uses: actions/checkout@v4
+      - name: Install Rust
+        run: rustup update stable
       - name: Add target
         run: rustup target add ${{ matrix.target }}
       - name: Build
         run: cargo build --release --target ${{ matrix.target }}
       
       - name: Check binary
-        run: ls -la target/${{ matrix.target }}/release/${{ env.BIN_NAME }}* || echo "binary not found in target/${{ matrix.target }}/release"
+        run: ls target/${{ matrix.target }}/release/${{ env.BIN_NAME }}* 2>/dev/null || echo "binary not found in target/${{ matrix.target }}/release"
       
       - name: Package (Unix)
         if: runner.os != 'Windows'
@@ -127,7 +129,7 @@ jobs:
       
       - name: Check file (Unix)
         if: runner.os != 'Windows'
-        run: ls -la ${{ env.BIN_NAME }}-${{ matrix.asset_suffix }}.tar.gz || echo "file not found"
+        run: ls ${{ env.BIN_NAME }}-${{ matrix.asset_suffix }}.tar.gz 2>/dev/null || echo "file not found"
       
       - name: Upload Artifact (Unix)
         if: runner.os != 'Windows'
@@ -144,7 +146,7 @@ jobs:
       
       - name: Check file (Windows)
         if: runner.os == 'Windows'
-        run: ls -la ${{ env.BIN_NAME }}-${{ matrix.asset_suffix }}.zip || echo "file not found"
+        run: ls ${{ env.BIN_NAME }}-${{ matrix.asset_suffix }}.zip 2>/dev/null || echo "file not found"
       
       - name: Upload Artifact (Windows)
         if: runner.os == 'Windows'
